name: l10n

on:
  pull_request:
    paths:
      - '.github/workflows/l10n.yml'
      - 'Makefile'
      - 'appinfo/**'
      - 'l10n/**'
      - 'lib/**'
      - 'src/**'
      - 'translationfiles/**'
  push:
    branches:
      - main
      - master
      - stable*

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    name: translations
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gettext

      - name: Build translations
        run: |
          make l10n
